Q3. Load the data from wine dataset. Check whether all attributes are standardized or not (mean
is 0 and standard deviation is 1). If not, standardize the attributes. Do the same with Iris dataset.

In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [2]:
data=datasets.load_wine()
df=pd.DataFrame(data.data,columns=data.feature_names)
df['output']=data.target
df
df2=df

In [3]:
#checking mean of all attributes
df.mean(axis=0)

alcohol                          13.000618
malic_acid                        2.336348
ash                               2.366517
alcalinity_of_ash                19.494944
magnesium                        99.741573
total_phenols                     2.295112
flavanoids                        2.029270
nonflavanoid_phenols              0.361854
proanthocyanins                   1.590899
color_intensity                   5.058090
hue                               0.957449
od280/od315_of_diluted_wines      2.611685
proline                         746.893258
output                            0.938202
dtype: float64

In [4]:
#checking standard deviation of all attributes
df.std(axis=0)

alcohol                           0.811827
malic_acid                        1.117146
ash                               0.274344
alcalinity_of_ash                 3.339564
magnesium                        14.282484
total_phenols                     0.625851
flavanoids                        0.998859
nonflavanoid_phenols              0.124453
proanthocyanins                   0.572359
color_intensity                   2.318286
hue                               0.228572
od280/od315_of_diluted_wines      0.709990
proline                         314.907474
output                            0.775035
dtype: float64

In [5]:
# standardizing with the help of StandardScaler
from sklearn.preprocessing import StandardScaler


In [6]:
scaler=StandardScaler()

In [7]:
df=scaler.fit_transform(df)
df

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  1.84791957,
         1.01300893, -1.21394365],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  1.1134493 ,
         0.96524152, -1.21394365],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.78858745,
         1.39514818, -1.21394365],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.48544548,
         0.28057537,  1.37386437],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.40069891,
         0.29649784,  1.37386437],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.42894777,
        -0.59516041,  1.37386437]])

In [8]:
scaler.mean_

array([1.30006180e+01, 2.33634831e+00, 2.36651685e+00, 1.94949438e+01,
       9.97415730e+01, 2.29511236e+00, 2.02926966e+00, 3.61853933e-01,
       1.59089888e+00, 5.05808988e+00, 9.57449438e-01, 2.61168539e+00,
       7.46893258e+02, 9.38202247e-01])

In [9]:
df.mean(axis=0)

array([-8.38280756e-16, -1.19754394e-16, -8.37033314e-16, -3.99181312e-17,
       -3.99181312e-17,  0.00000000e+00, -3.99181312e-16,  3.59263181e-16,
       -1.19754394e-16,  2.49488320e-17,  1.99590656e-16,  3.19345050e-16,
       -1.59672525e-16,  1.59672525e-16])

In [10]:
df.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Using mean method

In [11]:
normalized_df=(df2-df2.mean())/df2.std()
normalized_df

alcohol  malic_acid       ash  alcalinity_of_ash  magnesium  \
0    1.514341   -0.560668  0.231400          -1.166303   1.908522   
1    0.245597   -0.498009 -0.825667          -2.483841   0.018094   
2    0.196325    0.021172  1.106214          -0.267982   0.088110   
3    1.686791   -0.345835  0.486554          -0.806975   0.928300   
4    0.294868    0.227053  1.835226           0.450674   1.278379   
..        ...         ...       ...                ...        ...   
173  0.873810    2.966176  0.304301           0.300954  -0.331985   
174  0.491955    1.408636  0.413653           1.049555   0.158126   
175  0.331822    1.739837 -0.388260           0.151234   1.418411   
176  0.208643    0.227053  0.012696           0.151234   1.418411   
177  1.391162    1.578712  1.361368           1.498716  -0.261969   

     total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
0         0.806722    1.031908             -0.657708         1.221438   
1         0.567048    0.731565             -0.818411        -0.543189   
2         0.806722    1.212114             -0.497005         2.129959   
3         2.484437    1.462399             -0.979113         1.029251   
4         0.806722    0.661485              0.226158         0.400275   
..             ...         ...                   ...              ...   
173      -0.982841   -1.420891              1.270726        -0.927563   
174      -0.791103   -1.280731              0.547563        -0.316058   
175      -1.126646   -1.340800              0.547563        -0.420888   
176      -1.030776   -1.350811              1.351077        -0.228701   
177      -0.391646   -1.270720              1.592131        -0.420888   

     color_intensity       hue  od280/od315_of_diluted_wines   proline  \
0           0.251009  0.361158                      1.842721  1.010159   
1          -0.292496  0.404908                      1.110317  0.962526   
2           0.268263  0.317409                      0.786369  1.391224   
3           1.182732 -0.426341                      1.180741  2.328007   
4          -0.318377  0.361158                      0.448336 -0.037767   
..               ...       ...                           ...       ...   
173         1.139596 -1.388840                     -1.227742 -0.021890   
174         0.967055 -1.126341                     -1.481267  0.009866   
175         2.217979 -1.607590                     -1.481267  0.279786   
176         1.829761 -1.563840                     -1.396759  0.295664   
177         1.786626 -1.520090                     -1.424928 -0.593486   

       output  
0   -1.210529  
1   -1.210529  
2   -1.210529  
3   -1.210529  
4   -1.210529  
..        ...  
173  1.370000  
174  1.370000  
175  1.370000  
176  1.370000  
177  1.370000  

[178 rows x 14 columns]

In [12]:
normalized_df.std(axis=0)

alcohol                         1.0
malic_acid                      1.0
ash                             1.0
alcalinity_of_ash               1.0
magnesium                       1.0
total_phenols                   1.0
flavanoids                      1.0
nonflavanoid_phenols            1.0
proanthocyanins                 1.0
color_intensity                 1.0
hue                             1.0
od280/od315_of_diluted_wines    1.0
proline                         1.0
output                          1.0
dtype: float64

IRIS Dataset

In [13]:
from sklearn import datasets
data=datasets.load_iris()
df=pd.DataFrame(data.data,columns=data.feature_names)
df['output']=data.target
df2=df

In [14]:
df=scaler.fit_transform(df)

In [15]:
df.std(axis=0)

array([1., 1., 1., 1., 1.])

In [16]:
#mean method
normalized_data=(df-df.mean())/df.std()

In [17]:
normalized_data.std(axis=0)

array([1., 1., 1., 1., 1.])